In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import numba
import seaborn as sns

In [5]:
df=pd.read_csv(r'C:\Users\Home\Downloads\car_evaluation - car_evaluation.csv')
df.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [7]:
df.shape


(1727, 7)

In [8]:
col_name=['buying','maint','doors','persons','lug_boot','safety','class']
df.columns=col_name
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [10]:
df['buying'].value_counts()

high     432
med      432
low      432
vhigh    431
Name: buying, dtype: int64

In [11]:
for i in df.columns:
    print(i,':\n',df[i].value_counts())

buying :
 high     432
med      432
low      432
vhigh    431
Name: buying, dtype: int64
maint :
 high     432
med      432
low      432
vhigh    431
Name: maint, dtype: int64
doors :
 3        432
4        432
5more    432
2        431
Name: doors, dtype: int64
persons :
 4       576
more    576
2       575
Name: persons, dtype: int64
lug_boot :
 med      576
big      576
small    575
Name: lug_boot, dtype: int64
safety :
 med     576
high    576
low     575
Name: safety, dtype: int64
class :
 unacc    1209
acc       384
good       69
vgood      65
Name: class, dtype: int64


In [13]:
#Feature engineering

In [16]:
import category_encoders as cate

In [15]:
!pip install category_encoders

In [18]:
encode=cate.OrdinalEncoder(cols=['buying','maint','doors','persons','lug_boot','safety','class'])
df=encode.fit_transform(df)

In [19]:
for i in df.columns:
    print(i, ':\n', df[i].value_counts())

buying :
 2    432
3    432
4    432
1    431
Name: buying, dtype: int64
maint :
 2    432
3    432
4    432
1    431
Name: maint, dtype: int64
doors :
 2    432
3    432
4    432
1    431
Name: doors, dtype: int64
persons :
 2    576
3    576
1    575
Name: persons, dtype: int64
lug_boot :
 2    576
3    576
1    575
Name: lug_boot, dtype: int64
safety :
 1    576
2    576
3    575
Name: safety, dtype: int64
class :
 1    1209
2     384
4      69
3      65
Name: class, dtype: int64


In [20]:
encode=cate.OrdinalEncoder(cols=['class'])
df=encode.fit_transform(df)

In [21]:
 #Seperate the dataset

In [22]:
x=df.iloc[:, :-1]
y=df.iloc[:, -1:]

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rf=RandomForestClassifier(n_estimators=100,random_state=0)

In [27]:
rf.fit(x_train, y_train)
y_pred=rf.predict(x_test)

C:\Users\Home\AppData\Local\Temp/ipykernel_5080/3300661624.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(x_train, y_train)


In [29]:
from sklearn.metrics import accuracy_score

In [30]:
accuracy_score(y_test,y_pred)

0.9682080924855492

In [32]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 

In [33]:
print(confusion_matrix(y_test,y_pred,labels=[1,2,3,4]))
print(classification_report(y_test,y_pred))

[[237   0   0   0]
 [  0  75   1   1]
 [  0   4  12   1]
 [  0   1   3  11]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00       237
           2       0.94      0.97      0.96        77
           3       0.75      0.71      0.73        17
           4       0.85      0.73      0.79        15

    accuracy                           0.97       346
   macro avg       0.88      0.85      0.87       346
weighted avg       0.97      0.97      0.97       346

